services:

  php:
    image: ghcr.io/syntatis/php:7.4-fpm
    restart: on-failure
    volumes:
      - ../:/var/www/workspace
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - vscode_server_volume:/root/.vscode-server

volumes:
  vscode_server_volume:
